# Generated by Django 4.1.7 on 2023-03-16 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app_scraping', '0002_languageprogramm_alter_city_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(unique=True)),
                ('title', models.CharField(max_length=250, verbose_name='Заголовок вакансии')),
                ('company', models.CharField(max_length=250, verbose_name='Компания')),
                ('description', models.TextField(verbose_name='Подробное описание вакансии')),
                ('timestamp', models.DateField(auto_now_add=True)),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_scraping.city', verbose_name='Название города')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_scraping.languageprogramm', verbose_name='Язык программирования')),
            ],
            options={
                'verbose_name': 'Описание вакансии',
                'verbose_name_plural': 'Описание вакансий',
            },
        ),
    ]
