# Generated by Django 4.1.7 on 2023-03-18 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_scraping', '0003_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='salary',
            field=models.CharField(blank=True, max_length=250, verbose_name='Зарплата'),
        ),
    ]
